### ISSUE TITLE
Error: Cannot find module 'trim-right' when trying to convert a file to ts

### ISSUE THREAD

**Issue by davidfirst** [Khan/flow-to-ts#113]
I'm getting the following error when trying to convert a file.
I installed `flow-to-ts` globally as described in the README file.
Any idea?

```
➜  bit git:(master) ✗ flow-to-ts src/api.js
error processing src/api.js
{ Error: Cannot find module 'trim-right'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at _trimRight (/Users/davidfirst/.config/yarn/global/node_modules/@khanacademy/flow-to-ts/babel-generator/lib/buffer.js:9:39)
    at Buffer.get (/Users/davidfirst/.config/yarn/global/node_modules/@khanacademy/flow-to-ts/babel-generator/lib/buffer.js:47:17)
    at Generator.generate (/Users/davidfirst/.config/yarn/global/node_modules/@khanacademy/flow-to-ts/babel-generator/lib/printer.js:91:22)
    at Generator.generate (/Users/davidfirst/.config/yarn/global/node_modules/@khanacademy/flow-to-ts/babel-generator/lib/index.js:24:18)
    at _default (/Users/davidfirst/.config/yarn/global/node_modules/@khanacademy/flow-to-ts/babel-generator/lib/index.js:91:14)
    at convert (/Users/davidfirst/.config/yarn/global/node_modules/@khanacademy/flow-to-ts/src/convert.js:49:16) code: 'MODULE_NOT_FOUND' }
➜
```

**Comment by elzorrorebelde** [comment]
as a workaround I installed `trim-right` globally.

**Comment by k4b7** [comment]
Interesting.  I think why I haven't run into this yet is that running `yarn install` inside the repo installs both deps and dev deps.  The dev deps must also be using `trim-right` which is why it shows up in the yarn.lock file.

**Comment by joebowbeer** [comment]
The deps is coming from babel/generator, whose package.json is not installed; all of the subpackage deps need to be reflected in the root package.json

https://github.com/Khan/flow-to-ts/blob/master/babel-generator/package.json

You might look into using lerna to manage these packages.

**Comment by k4b7** [comment]
I've pushed 0.1.5 to github.

> The deps is coming from babel/generator, whose package.json is not installed; all of the subpackage deps need to be reflected in the root package.json

I've used yarn workspaces in the past for this kind of thing.  I thought lerna was just for publishing packages from monorepos.
