### ISSUE TITLE
Conversion fails when syntax uses decorators

### ISSUE THREAD

**Issue by eek** [Khan/flow-to-ts#143]
```
error processing blabla/blabla.js
{ SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (7:2)
    at Object.raise (/home/eek/.config/yarn/global/node_modules/@babel/parser/lib/index.js:7012:17)
    at Object.expectOnePlugin (/home/eek/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8420:18)
    at Object.parseDecorator (/home/eek/.config/yarn/global/node_modules/@babel/parser/lib/index.js:10872:10)
    at withTopicForbiddingContext (/home/eek/.config/yarn/global/node_modules/@babel/parser/lib/index.js:11475:32)
    at Object.withTopicForbiddingContext (/home/eek/.config/yarn/global/node_modules/@babel/parser/lib/index.js:10565:14)
    at Object.parseClassBody (/home/eek/.config/yarn/global/node_modules/@babel/parser/lib/index.js:11464:10)
    at Object.parseClass (/home/eek/.config/yarn/global/node_modules/@babel/parser/lib/index.js:11438:22)
    at Object.parseStatementContent (/home/eek/.config/yarn/global/node_modules/@babel/parser/lib/index.js:10732:21)
    at Object.parseStatement (/home/eek/.config/yarn/global/node_modules/@babel/parser/lib/index.js:10690:17)
    at Object.parseStatement (/home/eek/.config/yarn/global/node_modules/@babel/parser/lib/index.js:2079:26)
  pos: 124,
  loc: Position { line: 7, column: 2 },
  missingPlugin: [ 'decorators-legacy', 'decorators' ] }
```

Flow to TS seems to fail if the script uses decorators. 

Is there a way I can enable this babel plugin?

**Comment by lucaslim** [comment]
Interested to know if we can enable this plugin too

**Comment by sean-m-oleary** [comment]
i have the same issue. I've tried enabling the plugin but it still doesn't work

**Comment by eek** [comment]
I've solved it manually by modifying `/src/convert.js` and adding my plugins to the `parseOptions` 
https://github.com/Khan/flow-to-ts/blob/24be91eb73b9d2a248f5d538d2f1fd6425e1837e/src/convert.js#L9-L23

In my case, I've added there

```
    "decorators",
    "decorators-legacy",
```

And then using the `cli.js` from src to transform all my files.

**Comment by k4b7** [comment]
@eek I'm glad you found a solution.  Are both "decorators" and "decorators-legacy" always required or is this something that should be configurable?

**Comment by k4b7** [comment]
Does flow actually support decorators?  Can you post a snippet of the code that you're trying to convert?

**Comment by eek** [comment]
Hi @kevinbarabash 

Yeah, flow supports decorators.

I'm using decorators for MobX - you can find more here - https://mobx.js.org/refguide/observer-component.html

They look like this:

``` 
@observer
class Timer extends React.Component {
    render() {
        return <span>Seconds passed: {this.props.timerData.secondsPassed} </span>
    }
}
```

You indeed need both `decorators` and `decorators-legacy`, to be more exact, I'm using them on babel like this:

```
  babel: {
    plugins: [
      ['@babel/plugin-proposal-decorators', { legacy: true }]
    ]
  }
```
(this is an overwrite for create-react-app via craco)

**Comment by masylum** [comment]
I'm trying this workaround and actually babel complains that both can't be used at the same time:

```
Error: Cannot use the decorators and decorators-legacy plugin together
    at validatePlugins (/home/vagrant/.config/yarn/global/node_modules/@babel/parser/lib/index.js:7291:13)
    at getParser (/home/vagrant/.config/yarn/global/node_modules/@babel/parser/lib/index.js:12705:5)
    at parse (/home/vagrant/.config/yarn/global/node_modules/@babel/parser/lib/index.js:12688:12)
    at convert (/home/vagrant/.config/yarn/global/node_modules/@khanacademy/flow-to-ts/src/convert.js:30:15)
```

In my case, I've only enabled the legacy ones so I guess that should be configureable.

**Comment by aminya** [comment]
I have faced this issue too. I think the solution is just to add the decorator plugin to the dependencies of flow-to-ts

Here is a sample code.
https://github.com/nteract/hydrogen/blob/cdd0ba3526cdf82eddba8e538133a8c7c747687d/lib/components/output-area.js#L16

```js
error processing ./lib/store/watch.js
SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (29:2)
    at Object._raise (webpack://flowToTs/./babel/packages/babel-parser/src/parser/error.js?:84:17)
    at Object.raiseWithData (webpack://flowToTs/./babel/packages/babel-parser/src/parser/error.js?:76:17)
    at Object.expectOnePlugin (webpack://flowToTs/./babel/packages/babel-parser/src/parser/util.js?:150:18)
    at Object.parseDecorator (webpack://flowToTs/./babel/packages/babel-parser/src/parser/statement.js?:333:10)
    at eval (webpack://flowToTs/./babel/packages/babel-parser/src/parser/statement.js?:1021:32)
    at Object.withTopicForbiddingContext (webpack://flowToTs/./babel/packages/babel-parser/src/parser/expression.js?:2100:14)
    at Object.parseClassBody (webpack://flowToTs/./babel/packages/babel-parser/src/parser/statement.js?:1010:10)
    at Object.parseClass (webpack://flowToTs/./babel/packages/babel-parser/src/parser/statement.js?:979:22)
    at Object.parseExportDefaultExpression (webpack://flowToTs/./babel/packages/babel-parser/src/parser/statement.js?:1469:19)
    at Object.parseExportDefaultExpression (webpack://flowToTs/./babel/packages/babel-parser/src/plugins/flow/index.js?:1564:18) {
  loc: Position { line: 29, column: 2 },
  pos: 743,
  missingPlugin: [ 'decorators-legacy', 'decorators' ]
}

```
