### ISSUE TITLE
Crashes if you put a non-function before a function in a union

### ISSUE THREAD

**Issue by nickretallack** [Khan/flow-to-ts#153]
This works fine:
```
type Foo = (() => any) | any;
```
But this makes it crash:
```
type Foo = any | (() => any);
```
Like this:
```
$ flow-to-ts --prettier myfile.js
error processing myfile.js
{ SyntaxError: Type expected. (1:19)
> 1 | type Foo = any | () => any;
    |                   ^
    at t (/home/nretallack/.config/yarn/global/node_modules/prettier/parser-typescript.js:1:347)
    at Object.parse (/home/nretallack/.config/yarn/global/node_modules/prettier/parser-typescript.js:14:180461)
    at Object.parse (/home/nretallack/.config/yarn/global/node_modules/prettier/standalone.js:12055:21)
    at coreFormat (/home/nretallack/.config/yarn/global/node_modules/prettier/standalone.js:15572:25)
    at format (/home/nretallack/.config/yarn/global/node_modules/prettier/standalone.js:15832:75)
    at formatWithCursor (/home/nretallack/.config/yarn/global/node_modules/prettier/standalone.js:15848:14)
    at /home/nretallack/.config/yarn/global/node_modules/prettier/standalone.js:31794:17
    at Object.format (/home/nretallack/.config/yarn/global/node_modules/prettier/standalone.js:31802:14)
    at convert (/home/nretallack/.config/yarn/global/node_modules/@khanacademy/flow-to-ts/src/convert.js:68:21)
    at cli (/home/nretallack/.config/yarn/global/node_modules/@khanacademy/flow-to-ts/src/cli.js:82:23)
  loc: { start: { line: 1, column: 19 } },
  codeFrame: '> 1 | type Foo = any | () => any;\n    |                   ^' }
```

**Comment by k4b7** [comment]
I wasn't able to reproduce this in the latest version of the [playground](https://flow-to-ts.netlify.app/#code=Ly8gQGZsb3cKdHlwZSBGb28gPSBhbnkgfCAoKCkgPT4gYW55KTsK&prettier=1&semi=1&singleQuote=0&tabWidth=4&trailingComma=all&bracketSpacing=0&arrowParens=avoid&printWidth=80&inlineUtilityTypes=0).  @nickretallack can you update to the latest version and try again?

**Comment by k4b7** [comment]
I can't repro this in the command line tool either.  Please upgrade to the most recent release.
