### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by ThijSlim** [Khan/flow-to-ts#208]
On MacOS I am receiving the following error 

`
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:369:19)
    at cli (/usr/local/lib/node_modules/@khanacademy/flow-to-ts/src/cli.js:96:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/@khanacademy/flow-to-ts/src/flow-to-ts.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
`

when running the flow-to-ts command:

`
npm install -g @khanacademy/flow-to-ts
`
`
flow-to-ts --write --delete-source src
`

I am running it from the project repository and running it against the <project_repository>/src folder. I also tried adding a complete path.

**Comment by ThijSlim** [comment]
Fixed it by using a file Glob for all files in my directory

`flow-to-ts --write --delete-source **/*.jsx`
