### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by tomekxoxo** [Khan/flow-to-ts#361]
Hi, I repeated the steps shown in this article https://www.skovhus.dev/blog/flow-to-typescript-migration
Unfortunately, this is what I get.
```
npx @khanacademy/flow-to-ts --write  --delete-source src
internal/fs/utils.js:307
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at cli (webpack://flowToTs/./src/cli.ts?:72:62)
    at Object.<anonymous> (/Users/tomasz.kasprowicz/.npm/_npx/27519fef091b4faa/node_modules/@khanacademy/flow-to-ts/bin/flow-to-ts.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```
Thanks for help.

**Comment by nerami** [comment]
@tomekxoxo duplicated #208
